language: cpp
compiler:
    - gcc
before_install:
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "yast2-devtools doxygen pkg-config hwinfo-dev yast2-core-dev"
script:
    - make -s -f Makefile.cvs
    - make -s -j 4
    - sudo make -s install
    - make -s check

