language: cpp
compiler:
    - gcc
before_install:
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "yast2-devtools doxygen pkg-config hwinfo-dev yast2-core-dev"
script:
    - make -f Makefile.cvs
    - make -j 4
    - make check
    - sudo make install

